### ISSUE TITLE
brother-mfcj6520dw-(cupswrapper/lpr)

### ISSUE THREAD

**Issue by Nyx70** [fblog-repos/void-packages.base#11]
/usr/lib/cups/filter/brother_lpdwrapper_mfcj6520dw: 20: /usr/lib/cups/filter/brother_lpdwrapper_mfcj6520dw: cannot create /tmp/lp_xxxxxxxxx: Permission denied

**Comment by Monkey-7-12** [comment]
try: `sudo chmod 1777 /tmp`

**Comment by Nyx70** [comment]
🤦‍♂️ Thanks!
